feat(python): add lazyframe comparison operators
pola-rs/polars pull request #10275
Opened 2023-08-03 16:07 UTC by mcrumiller

Resolves #10274

@MarcoGorelli I mimicked the DataFrame comparison operators, with a couple of changes:

1. We can still immediately raise when columns do not match
2. For value and/or height differences, we cannot detect until `collect()` is called.
3. Regular DataFrame comparison operator uses `pl.concat("horizontal")` which isn't supported for lazy frames, so instead I did a quick drop-in of `df1.with_context(df2)`. This works well because it will error out when the heights don't match and will still raise a height/dtype difference exception.
4. The returned dataframe is still a boolean frame.

We may need more unit tests than I provided, but I wanted to get this out there for feedback.

2023-08-03 18:17 UTC, alexander-beedie commented
I don't think this makes sense. The equivalent analogy would be database tables that require a join in order to formalise the row-level relationships. Up until they are joined, there is no valid comparison 🤔

2023-08-03 18:40 UTC, mcrumiller commented
@alexander-beedie yup, I'll update to raise on these comparisons.

2023-08-03 18:45 UTC, mcrumiller commented
Question: do we want to return `False` if the comparator is not a lazy frame? In python we have:

```python
1 == date(2023, 1, 1) # False
1 == 'a' # False
...
```

...or should we just always raise a `TypeError`?

2023-08-03 18:53 UTC, alexander-beedie commented
I _think_ we should probably always raise `TypeError`; the other comparisons can raise `False` because there is a possibility of returning `True` when comparing against the correct type. Here, there isn't, and it would be a bit odd to return `False` when comparing against a different type, but only raise when comparing against like types.

2023-08-03 20:04 UTC, MarcoGorelli reviewed
Change looks good to me, just not sure about the phrasing " ambiguous LazyFrame structures" - is that used elsewhere? If not, maybe just "cannot compare LazyFrame structures"?

2023-08-03 20:06 UTC, mcrumiller commented
I'm open to anything, that's what I came up with on the spot. I agree that wording looks a bit confusing now. I think I was subconsciously influenced by the word "ambiguous" a few lines above...

2023-08-03 20:08 UTC, mcrumiller commented
Switched to a much simpler "Cannot compare LazyFrames; call .collect() to materialize."

2023-08-03 20:09 UTC, mcrumiller commented
Actually I'll drop the 2nd clause too.

2023-08-03 21:41 UTC, alexander-beedie commented
Can we reproduce the standard form of the error, which includes the operator? 
It's useful to see at a glance which operator is associated with the error.
I'd suggest the following template/example:
```
TypeError: "==" comparison not supported for LazyFrame objects.
```

2023-08-03 21:41 UTC, alexander-beedie requested changes
Nice, nearly there... one last change ;)

Let's reproduce the standard form of the error, which includes the operator. It's useful to see at a glance _which_ operator is associated with the error. I'd suggest the following template/example:
```
TypeError: "==" comparison is not valid/supported for LazyFrame objects.
```

2023-08-03 21:51 UTC, mcrumiller commented
@alexander-beedie good call, updated. Had to give each comparator its own function again, this way the correct symbol will be diplayed in the error message.

2023-08-04 06:19 UTC, alexander-beedie commented
> @alexander-beedie good call, updated. Had to give each comparator its own function again, this way the correct symbol will be diplayed in the error message, e.g.:
> 
> ```
> TypeError: "<=" comparison not supported for LazyFrame objects.
> ```

Looks good to me 👍

2023-08-04 06:19 UTC, merged