Standardize error message format
pola-rs/polars pull request #10470
Opened 2023-08-14 11:59 UTC by aminalaee

Closes https://github.com/pola-rs/polars/issues/10421

2023-08-14 12:02 UTC, ritchie46 commented on py-polars/polars/convert.py
> +        raise NoDataError("No rows. Cannot infer schema")
Should also remove the leading Capital.

2023-08-14 12:18 UTC, stinodego commented on py-polars/polars/utils/_parse_expr_input.py
> +            "\n\npl.lit or pl.col"
Your regexes are definitely leading to some false positives.

2023-08-14 12:20 UTC, stinodego requested changes
Thanks for the effort! Though I definitely see some issues still - messages that start with a capital letter, or mistakenly added newlines.

I'll put this on draft, just mark it ready-to-review when you've made a pass to verify your changes!

2023-08-14 12:32 UTC, alexander-beedie commented
Nice one! I was going to look at this but looks like you're off to a good start - go for it :))

2023-08-14 12:46 UTC, mcrumiller commented on py-polars/polars/dataframe/frame.py
> +                    "\n\nargument; Use columns: List[str]"
I think you put the newlines in the wrong place, should it not go after "argument"? Same with 952 below.

2023-08-14 12:48 UTC, mcrumiller commented
Out of curiosity, would we benefit from an error-helper function, or is this too much indirection? Something like

```python
pl.exceptions.raise(
    "ValueError",
    header="polars can not currently guarantee zero-copy conversion from Arrow for categorical columns",
    desc="Set `allow_copy=True` or cast categorical columns to string first."
)
```
Which could then ensure proper formatting, and insert newlines where appropriate?

2023-08-14 12:49 UTC, mcrumiller commented on py-polars/polars/dataframe/frame.py
> +                    "\n\nargument; Use columns: List[str]"
Edit: I see this was mentioned ago, and you regex'd this which makes sense. Carry on!

2023-08-14 13:04 UTC, alexander-beedie commented
> Out of curiosity, would we benefit from an error-helper function, or is this too much indirection? Something like

Perhaps, but it would find its way into the reported stack which isn't ideal.

2023-08-14 13:37 UTC, mcrumiller commented
@alexander-beedie there are ways to modify the traceback with the [`traceback`](https://docs.python.org/3/library/traceback.html) module, Jinja is well-known for doing this. But it's probably more effort than it's worth, especially if we want to be compatible on multiple versions.

2023-08-14 14:11 UTC, alexander-beedie commented
> @alexander-beedie there are ways to modify the traceback with the [`traceback`](https://docs.python.org/3/library/traceback.html) module, Jinja is well-known for doing this. But it's probably more effort than it's worth, especially if we want to be compatible on multiple versions.

Indeed; doing "clever" things with your exceptions IN your exception handling code is something I'm not a big fan of ;)

2023-08-15 23:50 UTC, stinodego approved these changes
Nice improvement!

I did have to fix a few false positives, and there are many messages that still do not conform to the guidelines. Plus the same improvements should be done on the Rust side. So the linked issue remains open for now.

If you wish to continue to work on the issue, I would advise a more concentrated approach: pick a module and make sure all error messages are perfect. That way, it's easier for us to review.

2023-08-16 00:18 UTC, merged

2023-08-16 00:26 UTC, mcrumiller commented
@aminalaee 55 files changed! Good job here. We all encounter error messages every day so this is a nice improvement :)

2023-08-16 05:07 UTC, aminalaee commented
Thanks for the review and kind words.
Yes I would love to keep working on the issue on both Python and Rust side and as you said it is better to go module by module as there are cases that are harder to find. For example I saw this by going through the files:


```py
msg = “Invalid operation”
raise ValueError(msg)
```