bug(python): raise IndexError on out of bounds series index
pola-rs/polars pull request #10502
Opened 2023-08-15 13:16 UTC by tjkuson

Closes #9877

2023-08-15 16:53 UTC, alexander-beedie requested changes
Nice; makes perfect sense that we should do this. Can you enrich the error slightly? Something like the following would provide additional useful pointers:

`IndexError(f"Series index {item} is out of bounds (len={self.len()})")`

2023-08-15 18:19 UTC, tjkuson commented
> Technically this is a breaking change as the `Exception` type is going to be different, so have tagged as such. Otherwise, this is looking good to me - thanks @tjkuson :)

Ah, sorry I missed that!

2023-08-16 00:16 UTC, stinodego requested changes
Thanks for the PR! However, I believe this is not the way to go.

You're checking explicitly for bounds, while this is already done in the `get_idx` method on the Rust side.

I think we should update the Rust side to throw a less generic error (`ComputeError` can be anything...), and then make the Rust binding emit an IndexError. The OverflowError happens before entering the Rust function - you can use try/except to catch it and convert to an IndexError.

2023-08-16 07:02 UTC, ritchie46 commented
Good point @stinodego. I think we should add an `PolarsError::OutOfBounds`, or make `PolarsError::ShapeMismatch` more generic.

2023-09-01 14:18 UTC, AdamBajger commented on py-polars/polars/series/series.py
> +                    )
How about a simple
```suggestion
           if (item % self.len) >= self.len:
               raise IndexError(
                  f"Series index {item} is out of bounds (len={self.len()})"
               )
```

2023-09-01 14:28 UTC, AdamBajger commented on py-polars/polars/series/series.py
> +                    )
I see, haven't read the previous replies. I might as well create my own merge request then...

2023-09-07 16:41 UTC, tjkuson commented
I have had a go at adding `PolarsError::OutOfBounds`, is this the preferred approach? Also, the GitHub Actions seems to be failing due to a spurious network error rather than the PR per se.

2023-09-12 03:40 UTC, stinodego commented
@tjkuson Thanks for the effort - this is in the right direction but doesn't really get there all the way. I opened https://github.com/pola-rs/polars/pull/11061 to finalize this fix.

2023-09-12 03:40 UTC, closed without merging