feat(rust, python): supports cast to list
pola-rs/polars pull request #10623
Opened 2023-08-20 11:27 UTC by reswqa

2023-08-20 11:42 UTC, reswqa commented
Something is unexpected, let me take a look.

2023-08-20 14:20 UTC, reswqa commented
Fixed on upstream in: https://github.com/jorgecarleitao/arrow2/pull/1550

2023-08-21 08:12 UTC, reswqa commented
Not entirely certain, but I assume that the failed workflow `Benchmark` is unrelated to this changes. 🤔

2023-08-21 11:47 UTC, reswqa commented
@ritchie46 Finally, all checks have passed. 😌

2023-08-21 17:48 UTC, stinodego requested changes
Great! Just a minor detail for the test case.

2023-08-21 18:28 UTC, reswqa commented on py-polars/tests/unit/datatypes/test_list.py
> +    assert df.to_dict(False) == {"a": [[1], [2], [3]]}
Really make sense!

2023-08-21 18:29 UTC, reswqa commented on py-polars/tests/unit/datatypes/test_list.py
> +    assert df.to_dict(False) == {"a": [[1], [2], [3]]}
I have updated this following this way.

2023-08-21 18:46 UTC, stinodego approved these changes
Great, thanks!

2023-08-21 19:01 UTC, merged