fix(python): fix missing timestamp cast in delta schema
pola-rs/polars pull request #10633
Opened 2023-08-20 15:36 UTC by ion-elgreco

In the recent change, there was fixed mapping between timestamps in ms/ns to us precision. However, delta-rs writes everything in non-timezone timestamps. So we can safely cast any timestamp, regardless of the timezone or precision to us precision. 

Changed the test cases to include time zones in some of them.

2023-08-21 17:45 UTC, stinodego requested changes
It's not clear to me now what happens with the time zones - are timezone-sensitive datetimes converted to naive datetimes? Or are they all set to UTC?

Please add a test that writes a delta table with a non-UTC datetime and reads it back, to show what the resulting schema looks like.

2023-08-21 18:20 UTC, ion-elgreco commented
> It's not clear to me now what happens with the time zones - are timezone-sensitive datetimes converted to naive datetimes? Or are they all set to UTC?
> 
> Please add a test that writes a delta table with a non-UTC datetime and reads it back, to show what the resulting schema looks like.

Delta protocol, only supports Timestamp with UTC and Timestamp with no TZ. 

Delta-RS implementation, however, has no support for Timestamp with UTC _yet_, only for Timestamp with no TZ. So that's why  everything needs to get casted to native datetimes.

I'll add the test case now.

2023-08-22 08:22 UTC, stinodego commented
Good work, @ion-elgreco !

I had to adjust the test because there is currently a bug in the Series constructor with time zones:
https://github.com/pola-rs/polars/issues/10662

Otherwise this looks great and is good to go!

2023-08-22 08:32 UTC, ion-elgreco commented
> Good work, @ion-elgreco !
> 
> I had to adjust the test because there is currently a bug in the Series constructor with time zones: #10662
> 
> Otherwise this looks great and is good to go!

Thanks @stinodego!

2023-08-22 08:34 UTC, stinodego commented
@ion-elgreco One more question: you mention `delta-rs` does not support time zones yet - is there a tracking issue for this? I'd like to add a TODO comment and link to the related issue.

If not, could you maybe create an issue in their repo and link it here?

2023-08-22 08:57 UTC, ion-elgreco commented
> @ion-elgreco One more question: you mention `delta-rs` does not support time zones yet - is there a tracking issue for this? I'd like to add a TODO comment and link to the related issue.
> 
> If not, could you maybe create an issue in their repo and link it here?

I had discussion with one of the maintainers in Slack before, but I've made an issue now on this: https://github.com/delta-io/delta-rs/issues/1598

2023-08-22 09:02 UTC, stinodego approved these changes

2023-08-22 09:03 UTC, stinodego commented
Thanks!

2023-08-22 09:19 UTC, merged