fix: improve error handling for malformed csv parsing
pola-rs/polars pull request #11035
Opened 2023-09-10 19:16 UTC by mrogowski11

Fixes #11019.

This pull request introduces two checks to enhance error handling when parsing CSV files, particularly in cases where quote characters are improperly placed:

1. **Global Scope Check (File-Level):** We now verify that the count of quote characters is even at the global, whole-file scope. An odd count of quote characters signifies a malformed CSV. Escaping a quote is achieved by doubling it (e.g., "ab""cd""de") and so the contract is upheld.
2. **Local Scope Check (Field-Level):** We examine the last character in each field, ensuring that it is a quote character. Additionally we confirm that the field length is at least 2 bytes. This prevents situations where a field consists solely of a quote character. This check is performed if the first byte of a field is a quote character.

Both tests are performed only if `quote_char == Some(x)`.

The checks improve an error handling when trying to parse csv like:
```
a,b,c
A,"B,C
```  
or:
```
a,b,c
A,"B,"C  
```

2023-09-11 09:32 UTC, orlp commented
I don't think the way to do this is by adding a pass over the entire file just to count the number of quote characters. This could read gigabytes of data.

2023-09-11 10:06 UTC, ritchie46 commented
This is indeed way too expensive. Error's are allowed to do some compute, but they can be catched and handled and should not cause the huge wall times.

2023-09-11 10:45 UTC, mrogowski11 commented
Maybe only performing the second check is the way. This option is more efficient since it examines the last byte (unless it's escaped) of fields that have already been iterated. This check can handle situations like the one mentioned in the issue. While skipping the first check might allow some corner cases, I don't see a more performance-friendly approach without making significant changes to existing structures.

2023-09-12 07:16 UTC, ritchie46 commented on crates/polars-io/src/csv/parser.rs
> +                    if needs_escaping && !ignore_errors {
I don't want an extra branch in the hot loop. This will slow down parsing well formed csv files.

2023-09-12 07:19 UTC, ritchie46 requested changes

2023-09-12 07:19 UTC, ritchie46 commented on crates/polars-io/src/csv/read_impl/mod.rs
> +        if !self.ignore_errors {
I don't want this. This does a whole scan of the file.

The csv-parser is designed to be fast for correct files. This isn't a csv-file sanitizer.

2023-09-12 10:13 UTC, closed without merging