style(rust): standardize error message format
pola-rs/polars pull request #11720
Opened 2023-10-13 22:00 UTC by TheDataScientistNL

This code change updates all error messages in the rust part of polars package; see #10421

2023-10-15 17:09 UTC, TheDataScientistNL commented
@stinodego I have added many Rust error standardization corrections. Could you have a look? Not sure why the ubuntu 3.11 python tests fail. I have not, as far as I can see, changed anything that would result in the failing of a test with a `null` vs 0, and hesitant to push a fix....

2023-10-15 17:52 UTC, stinodego commented
That's an unrelated bug caught by our parametric tests - don't worry about it! I'll review this soon.

2023-10-16 01:58 UTC, orlp commented
This is a nitpick, but could you remove the periods from the end of error messages?

2023-10-16 02:00 UTC, stinodego commented
> This is a nitpick, but could you remove the periods from the end of error messages?

Most don't have a period, right? The help text should have proper punctuation though. See https://github.com/pola-rs/polars/issues/10421

2023-10-16 06:54 UTC, ritchie46 commented
The single line messages shouldn't right?

2023-10-16 06:59 UTC, stinodego commented
> The single line messages shouldn't right?

Correct. From the linked issue:

> * The error message starts with a single sentence, without capitalization or trailing period.
> * If further elaboration is required, two newlines are added before adding further text with proper capitalization and punctuation.

2023-10-18 09:47 UTC, stinodego requested changes
A lot of improvements, but a lot of messages are now less clear because you stitched multi-sentence error messages together, instead of breaking them up into a short summary and a help text. Also, a lot of code snippets are still not in backticks.

This PR is too big for me to sit down and go through every example and correct the messages that I feel are regressions. Please break this up into multiple PRs, let's say one per crate, and really take care that the messages are high quality. Then we can actually get some of this work merged!

2023-10-18 09:47 UTC, stinodego commented on crates/polars-arrow/src/array/list/mod.rs
> +            polars_bail!(ComputeError: "ListArray's child's DataType must match, yet the expected DataType is {child_data_type:?} while it got {values_data_type:?}");
This is too long for a single line error message. It should be broken up into a summary and a help text.

2023-10-18 09:47 UTC, stinodego commented on crates/polars-arrow/src/array/map/mod.rs
> +            polars_bail!(ComputeError: "the data_type's logical type must be DataType::Map")
Code snippets must be in backticks.

```suggestion
            polars_bail!(ComputeError: "the data_type's logical type must be `DataType::Map`")
```

2023-10-18 11:35 UTC, TheDataScientistNL commented
> A lot of improvements, but a lot of messages are now less clear because you stitched multi-sentence error messages together, instead of breaking them up into a short summary and a help text. Also, a lot of code snippets are still not in backticks.
> 
> This PR is too big for me to sit down and go through every example and correct the messages that I feel are regressions. Please break this up into multiple PRs, let's say one per crate, and really take care that the messages are high quality. Then we can actually get some of this work merged!

Will do.

2023-10-18 17:42 UTC, closed without merging