docs: fix incorrect example of valid time zones
pola-rs/polars pull request #11873
Opened 2023-10-19 22:26 UTC by romanovacca

fix #11774

Doubt the `;` were intended, so replaced them by `.`

2023-10-19 22:57 UTC, stinodego requested changes
Thanks! Just one comment.

2023-10-19 22:57 UTC, stinodego commented on docs/user-guide/transformations/time-series/timezones.md
> -  format above instead as it will deal with irregularities such as DST (Daylight Saving Time) for you.
We should probably state explicitly that this is NOT supported.

2023-10-19 23:08 UTC, stinodego approved these changes
Thanks!

2023-10-20 04:53 UTC, ritchie46 approved these changes

2023-10-20 04:53 UTC, merged