fix(rust,python): Consistently propagate nulls for `numpy` ufuncs
pola-rs/polars pull request #12212
Opened 2023-11-03 00:35 UTC by rob-sil

Closes #10233 

When applying a `numpy` ufunc to a series, the resulting series would get its validity mask from only the first series in the argument list. If there were multiple series arguments, then the null values in those other series would all be treated like zeros.

This PR makes sure that output will be null anywhere one of the inputs is null, not just where the first one is. Sometimes ufuncs will treat nulls like the equivalent polars functions, like how both `numpy.add` and series addition propagate null values. However, that's not the case for the function in the linked issue, where `numpy.maximum` propagates null values but `pl.max_horizontal` ignores them. At least `numpy.maximum` won't depend on the argument order anymore.

In the course of fixing this bug, I also added boolean and null values to the type hint for `Series.set`. Both work, since `set_with_mask_bool` supports `bool` values and all the `set_with_mask_` functions can take null values. In those cases, I noticed that `set` was dropping the name of the series and fixed that.

2023-11-03 14:34 UTC, orlp requested changes

2023-11-03 14:34 UTC, orlp commented on py-polars/polars/series/series.py
> +            null_mask = self.is_null()
Could you write this in terms of `is_not_null` and `&=`? Polars internally stores validity masks in this manner.

2023-11-03 14:34 UTC, orlp commented on py-polars/polars/series/series.py
> +            return self._from_pyseries(series).set(null_mask, None)
You'll have to change this to `pl.when(not_null_mask).then(series)` or similar.

2023-11-03 21:25 UTC, orlp approved these changes

2023-11-05 13:01 UTC, ritchie46 commented
Thank you for the PR @rob-sil

2023-11-05 13:01 UTC, merged