refactor: simplify expr checking in predicate push down
pola-rs/polars pull request #12287
Opened 2023-11-07 09:51 UTC by nameexhaustion

Resolves https://github.com/pola-rs/polars/issues/12116, this mainly does some refactoring around the utility functions in predicate pushdown.

### Consolidation of checking for boundary predicates
Consolidates the following 3 functions into a single function `aexpr_blocks_predicate_pushdown`:
* `predicate_is_pushdown_boundary`
* `projection_is_definite_pushdown_boundary`
* `partition_by_full_context`

The new function is only called from 2 places:
* Under `push_down::match::Selection`, which checks all predicate exprs and blocks pushdown appropriately if needed
* Under `pushdown_and_continue`, which checks all projection exprs and blocks pushdown appropriately if needed

Otherwise, any previous usage of the 3 removed functions are replaced by an assertion `assert_aexpr_allows_predicate_pushdown`, since boundary exprs are not expected outside the above 2 contexts.

### Refactor handling of predicate re-naming during pushdown
- renames function `projection_is_optional_pushdown_boundary` to `projection_allows_aliased_predicate_pushdown` to better express its intent, and refactor the matching to allow Column or Alias expressions rather than disallowing other functions. It also inverts the meaning of its previous boolean return value (i.e. `true` means pushdown is allowed rather than blocked).
- renames variable `projection_maybe_boundary` to `allow_aliased_pushdown` (meaning is also inverted)

### Other
- perf: re-enable row count predicate pushdowns for Parquet and IPC scans, as they are known to apply predicates after updating the row counts (was disabled for all scans earlier due to being incorrect for CSV scanning)

2023-11-07 09:57 UTC, stinodego commented
> failing tests (`check-features`) appear to be unrelated

These failures usually _are_ related and it means a feature flag is messed up somewhere. Though I don't immediately see what the cause would be here.

2023-11-07 12:46 UTC, stinodego commented on py-polars/tests/unit/io/test_lazy_parquet.py
> +def test_row_count_predicate_pushdown(tmp_path: Path) -> None:
I also don't immediately see what's wrong here.

2023-11-07 14:26 UTC, stinodego commented on py-polars/tests/unit/io/test_lazy_parquet.py
> +def test_row_count_predicate_pushdown(tmp_path: Path) -> None:
Right - maybe open a bug report issue and include the test. It doesn't need to block this PR.

2023-11-07 17:31 UTC, ritchie46 requested changes
Thanks! Nice cleanup! I've left a few comments.

2023-11-07 17:31 UTC, ritchie46 commented on crates/polars-plan/src/logical_plan/optimizer/predicate_pushdown/utils.rs
> +        assert_aexpr_allows_predicate_pushdown(*projection_node, expr_arena);
Can we only call this an compile the function when `debug_assertions` e.g. in debug mode. I don't want every node to call this as it does allocations and traversals and there are users with a lot of column projections.

2023-11-07 17:31 UTC, ritchie46 commented on crates/polars-plan/src/logical_plan/optimizer/predicate_pushdown/utils.rs
> +    for (_, ae) in expr_arena.iter(node) {
Can we use `has_aexpr(node, arena, |ae| !matches!(...))` here?

2023-11-07 17:31 UTC, ritchie46 commented on crates/polars-plan/src/logical_plan/optimizer/predicate_pushdown/utils.rs
> +                let values = input.get(1).unwrap();
Can we branch here instead of `unwrap`. There are cases where we don't have input expressions.

2023-11-08 06:50 UTC, ritchie46 approved these changes

2023-11-08 06:50 UTC, merged