fix(rust,python): expose `head`/`tail` directly to `Series`
pola-rs/polars pull request #12946
Opened 2023-12-07 17:09 UTC by mcrumiller

Resolves #12928.

2023-12-07 17:51 UTC, stinodego commented on py-polars/src/series/mod.rs
> +    }
The input here is not an Option type (same for tail):

```suggestion
    fn head(&self, n: usize) -> Self {
        self.series.head(Some(n)).into()
    }
```

2023-12-07 17:51 UTC, stinodego requested changes
I wonder why dispatching to DataFrame is so much slower? :thinking:

2023-12-07 17:55 UTC, mcrumiller commented
> I wonder why dispatching to DataFrame is so much slower? 🤔

From my research it's due to `select` taking up all of the time. If we want to solve this issue for other cases, it might be worth having a behind-the-scenes fast path for single-column selection by name into an ldf.

2023-12-07 17:58 UTC, stinodego approved these changes
Right, we'll have to put some thought into the dispatching. Especially when it comes to often-used/cheap methods.

2023-12-07 18:14 UTC, CaselIT commented
> I wonder why dispatching to DataFrame is so much slower? 🤔

Doing the more naive version seems to be very fast
(on a different pc)
```py
go("plain_series.head(0)")
go("plain_series.head(100)")
go("plain_series.tail(0)")
go("plain_series.tail(100)")
go("plain_series.to_frame().head(0).to_series()")
go("plain_series.to_frame().head(100).to_series()")
go("plain_series.to_frame().tail(0).to_series()")
go("plain_series.to_frame().tail(100).to_series()")
```
```
plain_series.head(0) 4.969168399926275
plain_series.head(100) 5.323634900152683
plain_series.tail(0) 5.622998500009999
plain_series.tail(100) 5.60176460002549
plain_series.to_frame().head(0).to_series() 0.14708300004713237
plain_series.to_frame().head(100).to_series() 0.15118449996225536
plain_series.to_frame().tail(0).to_series() 0.1474038001615554
plain_series.to_frame().tail(100).to_series() 0.14568820013664663
```

2023-12-07 22:52 UTC, mcrumiller commented
I've added direct dispatch to a lot more Series functions, will update momentarily.

2023-12-07 22:55 UTC, stinodego commented
> I've added direct dispatch to a lot more Series functions, will update momentarily.

That's a bit premature. I'd like to discuss this with the team first.

2023-12-07 22:57 UTC, mcrumiller commented
Hi @stinodego, no problem. I had assumed that any argument for direct dispatch to `head`/`tail` could also be applied to any arbitrary function, but I can see why we wouldn't want to add code bloat for minor performance improvements. For the record, here is what I have in my commit (but have not pushed):

* `head`
* `tail`
* `any`
* `all`
* `product`
* `nan_max`
* `nan_min`
* `std`
* `var`
* `cut`
* `qcut`
* `value_counts`
* `entropy`
* `is_between`
* `slice`

2023-12-07 23:24 UTC, mcrumiller commented
I'll push for now so it's easier to gauge the impact, we can always revert anything we need.

2023-12-11 08:36 UTC, ritchie46 commented
@mcrumiller can you revert this PR to the head and tail then we can merge this? You can open an issue for the other ones.

2023-12-11 14:48 UTC, stinodego approved these changes

2023-12-11 14:49 UTC, merged