feat(python): Allow renaming expressions through keyword arg syntax in `group_by`
pola-rs/polars pull request #13415
Opened 2024-01-03 17:21 UTC by deanm0000

fixes https://github.com/pola-rs/polars/issues/11957

This adds named arguments to group_by.  One thing I noticed was that in eager mode there are some checks to enforce a rule that there can't be any expressions in the group_by if doing a map_groups whereas there are no such checks with lazy. It seems to me that enforcing that rule isn't necessary and that it would be better to either add an implicit `with_columns` which would add their expressions to the df before the next step or just documenting that whatever columns they're creating in the group_by won't be available although the groups will be as defined by those expressions.

Separately, I have two newbie problems that I'm not sure I need to do anything about. I see that my linter has reformatted a few lines so there are fewer line breaks. Additionally, it looks like some of the changes I made in another PR are showing up here, I'm not sure if that's git being smart doing expected things or if I did something wrong here.

2024-01-03 17:35 UTC, MarcoGorelli commented
> Additionally, it looks like some of the changes I made in another PR are showing up here, I'm not sure if that's git being smart doing expected things or if I did something wrong here.

looks like you've got some commits here from your other branch, I'd suggest doing a rebase onto `upstream/main`

2024-01-03 20:21 UTC, deanm0000 commented
@MarcoGorelli I think I was supposed to switch back to main before making this branch so I reverted those commits from this one so it should be good now...other than the question about different behavior between eager and lazy.

2024-01-03 22:16 UTC, stinodego requested changes
I'll come back to you on the lazy vs eager issue.

2024-01-03 22:16 UTC, stinodego commented on py-polars/polars/lazyframe/frame.py
> +        **named_more_by: IntoExpr,
This should be `**named_by` (here and everywhere else).

2024-01-04 07:18 UTC, stinodego commented on py-polars/polars/dataframe/group_by.py
> +        if len(self.named_more_by) > 0:
```suggestion
        if self.named_more_by:
```

2024-01-04 07:21 UTC, stinodego commented on py-polars/polars/dataframe/group_by.py
> +                "cannot call `map_groups` when grouping with named expressions"
You can just reuse the message used for the other errors here, it's clear enough. Even better: declare a `msg` variable with this string and re-use it in all 3 error messages.

2024-01-04 07:22 UTC, stinodego commented on py-polars/polars/dataframe/group_by.py
> +        # but it is inconsistent with lazy which has no such checks.
These comments should be removed. Such discussion is best left for PR comments.

2024-01-04 16:38 UTC, deanm0000 commented
I get why the checks are there, I'll open another issue with more examples and leave those checks there for now.

2024-01-04 17:25 UTC, stinodego commented
@deanm0000 Could you rebase this and add a test?

2024-01-04 18:46 UTC, deanm0000 commented
I see my tests are failing, I'll pick it up tomorrow or next week.

2024-01-05 11:14 UTC, stinodego commented
It seems you've made some error in rebasing your branch - I don't thiink there's not actually 34 commits on your branch. It also looks like the conflicts were not handled correctly.

I also just noticed: we should be removing the `by` keyword argument, and deprecate its use properly. Signature should become `*by, **named_by`.

> I'll pick it up tomorrow or next week.

Sure, tag me if you want me to review.

2024-01-29 14:57 UTC, deanm0000 commented
replaced with https://github.com/pola-rs/polars/pull/14071

2024-01-29 14:57 UTC, closed without merging