fix(python): ensure the `cs.temporal()` selector wildcards Datetime the time_zone match
pola-rs/polars pull request #13683
Opened 2024-01-12 16:43 UTC by alexander-beedie

Closes  #13665.

We weren't matching `Datetime` dtypes _with_ time zones when using the `cs.temporal()` selector (or `DATETIME_DTYPES` and `TEMPORAL_DTYPES` dtype sets). 

Ensuring that we additionally match using the `time_zone="*"` wildcard fixes this.

2024-01-12 20:12 UTC, stinodego commented
I don't know about this as `Datetime(time_zone="*")` is not a valid data type.

2024-01-12 20:18 UTC, alexander-beedie commented
> I don't know about this as `Datetime(time_zone="*")` is not a valid data type.

I did think about this, but if you're using a `DataTypeGroup` the chances are high that you're matching, in which case you don't want to miss valid dtypes. And you can't directly assign a group as part of a schema (or series). In case you do want only valid dtypes I added "_NO_WILDCARDS" variants for that case 👍

2024-01-12 20:20 UTC, stinodego commented
I don't really know what you mean by matching - `pl.Datetime("us", "UTC") in pl.TEMPORAL_DTYPES` already 'matches' as it returns True by grace of the special `__eq__` implementation.

2024-01-12 20:21 UTC, alexander-beedie commented
> I don't really know what you mean by matching - `pl.Datetime("us", "UTC") in pl.TEMPORAL_DTYPES` already 'matches' as it returns True by grace of the special `__eq__` implementation.

eg: `pl.col(TEMPORAL_DTYPES)`

But I don't mind having the wildcard logic live only in `selectors` if there's too much potential for other issues.

2024-01-12 20:24 UTC, stinodego commented
If those data type groups were internal I would be fine with it, but they are part of the public API (which I am not too sure about actually). So they shouldn't contain invalid types just because we need that in our internal logic. No user can really do anything with a `Datetime(time_zone="*")`, right?

2024-01-12 20:33 UTC, alexander-beedie commented
> If those data type groups were internal I would be fine with it, but they are part of the public API (which I am not too sure about actually). So they shouldn't contain invalid types just because we need that in our internal logic. No user can really do anything with a `Datetime(time_zone="*")`, right?

Indeed; but my contention is that the majority use-case for `DataTypeGroup` is `pl.col(<group>)` matching rather than iterating out valid dtypes, and for that you really should have the wildcard. If you want the other, you can iterate over `DATETIME_NO_WILDCARDS` or `TEMPORAL_NO_WILDCARDS` instead.

2024-01-12 22:38 UTC, mcrumiller commented
This might be a somewhat wonky suggestion, but what if we were to distinguish a generic `pl.Datetime` from a `pl.Datetime(time_zone=None)`? The former would resolve to the latter when setting the dtype of a particular column (i.e. `pl.Series(..., dtype=pl.Datetime) creates a dtype with no time zone), but for selection/matching, `pl.Datetime` by itself is the equivalent of Alex's "*", and acts as a supertype for all `Datetime`s. This can be done pretty easily with the (albeit somewhat ugly) marker default parameters:

```python
class Datetime:
    _tz_supplied = False
    __marker = object()

    def __init__(time_unit=None, time_zone=__marker):
        self._tz_supplied = time_zone is __marker
```

...or something of the sort.

2024-01-19 15:56 UTC, MarcoGorelli commented
I think a wildcard is quite nice here - `'*'` isn't the name of any time zone (https://en.wikipedia.org/wiki/List_of_tz_database_time_zones), so there's no ambiguity

2024-03-01 10:42 UTC, stinodego requested changes
I really want to avoid adding these "NO_WILDCARD" constants to the public API. I feel like we have to rethink things a bit more thoroughly and I don't want to add more stuff that we might have to deprecate later.

Let's just restore the `DATETIME_DTYPES` variable and explicitly specify the dtypes in that one parametric test, and then we can revisit this later.

2024-03-21 08:50 UTC, stinodego approved these changes

2024-03-21 09:09 UTC, merged