fix(rust, python): treat null columns as zero in `sum_horizontal`
pola-rs/polars pull request #13880
Opened 2024-01-20 23:50 UTC by edavisau

Fixes #13113 

- Null columns are treated as additive identity in the presence of non-null columns. They can be skipped in the computation
- If all columns are Null, return Null

I have also changed the behaviour of single columns sums. This seems more consistent to multi-column sums. Example:

```python
    df = pl.DataFrame(
        {
            "A": [5, None, 3, None],
            "B": [5, 3, None, None],
        }
    )
```

As reference, when summing multiple columns
`sum_horizontal("A", "B") = [10, 3, 3, 0]`

Before
 `sum_horizontal("A") = [5, None, 3, None]`
After
 `sum_horizontal("A") = [5, 0, 3, 0]`

2024-01-21 03:22 UTC, stinodego commented
Thanks for the PR!

> If all columns are Null, return Null

I don't think this is correct. Null should just be treated as the identity always.

2024-01-21 03:35 UTC, stinodego requested changes
Thanks for the PR!

> If all columns are Null, return Null

I don't think this is correct. Null should just be treated as the identity always.

2024-01-21 03:43 UTC, edavisau commented
@stinodego  In this case I was referring to the actual Null data type, as opposed to all values being null i.e.
```python
df = pl.DataFrame([
    pl.Series("A", [None, None, None], pl.Null),
    pl.Series("B", [None, None, None], pl.Null),
    pl.Series("C", [None, None, None], pl.Null),
])
```

If you replaced `pl.Null` with `pl.Int32` above you'll get 0 in the result, similarly if you replaced with `pl.Utf8` you'll get empty strings in the result. In addition, if 2 of the columns were pl.Null, and one was pl.Int32, you'd still get a pl.Int32 result. The all-pl.Null situation seemed too ambiguous though. Do you have another suggestion for this case?

Thanks!

2024-01-21 03:47 UTC, stinodego commented
Ah, I hadn't understood that part. Then it's probably fine!

2024-01-22 07:39 UTC, ritchie46 approved these changes
Thanks!

2024-01-22 07:39 UTC, merged