feat(python): Add `read_clipboard` and `DataFrame.write_clipboard`
pola-rs/polars pull request #15272
Opened 2024-03-25 07:32 UTC by CanglongCl

**Issue #9902**

Similar to [`pandas.DataFrame.to_clipboard`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_clipboard.html#pandas.DataFrame.to_clipboard) and [`pandas.read_clipboard`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_clipboard.html), `read_clipboard` reads csv format text from clipboard and convert it into `DataFrame` whereas `DataFrame.write_clipboard` writes `DataFrame` into clipboard with csv format. 

These 2 methods are useful while exploring data from Excel or other similar software in interactive environment like jupyter notebook. 

# Implementation

- Reading and writing clipboard uses [arboard](https://github.com/1Password/arboard) in rust side, supporting Windows, macOS and Linux, maintained by 1Password. 
- `read_clipboard` is just read the clipboard then pass the result to `read_csv` with default separator `'\t'`.
- `write_clipboard` is just getting csv string by calling `DataFrame.write_csv` (but with default separator `'\t'`) and write to clipboard. 

# Difference from `pandas` method

`pandas.read_clipboard` uses regex `'\\s+'` as separator, but `polars` does not allow regex as separator in `read_csv`. 

# Compatibility

Tested Compatible: 
- Microsoft Excel (Mac)
- Google Sheet (Online)
- WPS (Online)

# Others

Both methods are only tested on M1 macOS. It would be much appreciated if someone could test on Linux and Windows.

2024-03-26 14:30 UTC, ritchie46 commented
I am not convinced by this one. Two things I am concerned about. 

- New dependencies and binary size. (Can you check how much this increments by the new dependencies)
- Why default to tab separated data? What do we think about limited dtype support?

2024-03-26 15:54 UTC, orlp requested changes

2024-03-26 15:54 UTC, orlp commented on Cargo.toml
> +arboard = { version = "3.3.2" }
Please use `optional-features = false`, we don't need the image copy/paste capabilities - it pulls in a lot of extra dependencies.

2024-03-27 14:22 UTC, cjackal commented
> * Why default to tab separated data?

Adding to @CanglongCl 's, rendered html table is another source of clipboard I/O which defaults to tab separator. "I/O of tsv strings via clipboard" is the force of nature, I think.

2024-04-01 12:22 UTC, ritchie46 commented
Alright. Let's give this a try. I understand why this can be nice. Thank you @CanglongCl

2024-04-01 12:22 UTC, ritchie46 approved these changes

2024-04-01 12:23 UTC, merged