fix: `to_any_value` should supports all LiteralValue type
pola-rs/polars pull request #15387
Opened 2024-03-29 07:38 UTC by reswqa

This fixes #15379.

2024-03-29 08:19 UTC, stinodego requested changes
I think we should instead implement `to_any_value` for the missing types. Should be easy enough - Series and Range become a List type AnyValue, and Binary becomes a Binary AnyValue.

2024-03-29 12:57 UTC, stinodego commented on crates/polars-plan/src/logical_plan/lit.rs
> +                };
I think you can use just `new_int_range` here, right?

2024-03-29 20:12 UTC, stinodego approved these changes
Looks good! Nice that we can use `repeat` on list inputs now 👌

2024-03-29 20:12 UTC, stinodego approved these changes
Looks good! Nice that we can use `repeat` on list inputs now 👌

2024-03-31 07:59 UTC, ritchie46 approved these changes

2024-03-31 07:59 UTC, merged