feat(python, rust): use `Series.sort` in `top_k`
pola-rs/polars pull request #15488
Opened 2024-04-05 05:35 UTC by CanglongCl

This allows more dtype to use `top_k` which only supported numeric dtypes before.

2024-04-05 09:53 UTC, stinodego reviewed
This is not a valid solution. The whole point of `top_k` is that it is more efficient than `sort` followed by `head`.

2024-04-05 23:09 UTC, CanglongCl commented
> Thanks for the PR, but this is not a valid solution. The whole point of `top_k` is that it is more efficient than `sort` followed by `head`.
> 
> If we want to support more datatypes in `top_k`, we should implement the algorithm for those datatypes. Booleans can have a dedicated fast implementation because we know there are only two possible values. For strings, I don't know the correct approach.

Thanks for review. I've rewrite the pr. `binary` and `string` now using the same algorithm with numeric types.

2024-04-06 15:19 UTC, ritchie46 requested changes

2024-04-06 15:19 UTC, ritchie46 commented on crates/polars-ops/src/chunked_array/top_k.rs
> +        upper.sort_unstable_by(|a, b| cmp(a, b).reverse());
```suggestion
        upper.sort_unstable_by(|a, b| cmp(b, a));
```

2024-04-06 15:19 UTC, ritchie46 commented on crates/polars-ops/src/chunked_array/top_k.rs
> +            let mut new_ca: BooleanChunked = iter::repeat(None)
Can we rewrite this by extending to a `MutableBooleanArray instead of `chain`ing iterators? These `chains` are not without cost.

2024-04-06 15:19 UTC, ritchie46 commented on crates/polars-ops/src/chunked_array/top_k.rs
> +        let mut v = ca.iter().collect::<Vec<_>>();
Can you use `downcast_iter` and `extend`? Similar to the non null branch. Flattening the loops is not without cost.

2024-04-07 08:42 UTC, ritchie46 requested changes
Almost there. Only one remark on the string path.

2024-04-07 08:42 UTC, ritchie46 commented on crates/polars-ops/src/chunked_array/top_k.rs
> +            top_k_binary_impl(&s.str().unwrap().as_binary(), k as usize, descending)
First we should call `to_string` here to go back to string without doing utf8 validation.

2024-04-07 08:42 UTC, ritchie46 commented on crates/polars-ops/src/chunked_array/top_k.rs
> +    match src.is_sorted_flag() {
Good observation. :+1:

2024-04-07 08:48 UTC, ritchie46 commented on crates/polars-ops/src/chunked_array/top_k.rs
> +            downcast_as_macro_arg_physical!(&s, dispatch).cast(origin_dtype)
I know this was already using `cast`, but let's `cast_unchecked` here as we know we don't change the type.

2024-04-08 06:17 UTC, ritchie46 approved these changes
Alright. Going in. Thank you!

2024-04-08 06:18 UTC, merged