fix(python): raise if DF is input to context (with_columns, select, etc)
pola-rs/polars pull request #15598
Opened 2024-04-11 17:44 UTC by deanm0000

addresses https://github.com/pola-rs/polars/issues/15588

2024-04-11 19:51 UTC, MarcoGorelli commented
nice - fancy adding a little test too?

2024-04-11 19:55 UTC, deanm0000 commented
A test to verify that it errors?

2024-04-11 20:20 UTC, MarcoGorelli commented
Yup, you can use the pytest.raises context manager

2024-04-11 20:44 UTC, deanm0000 commented
well that was a good callout b/c there was a way that is snuck by that is now fixed.

2024-04-12 06:09 UTC, ritchie46 commented on py-polars/polars/_utils/parse_expr_input.py
> +        msg = "A DataFrame is an invalid input"
```suggestion
        msg = "a DataFrame is an invalid input"
```

2024-04-12 06:09 UTC, ritchie46 commented on py-polars/polars/_utils/parse_expr_input.py
> +        msg = "A LazyFrame is an invalid input"
```suggestion
        msg = "a LazyFrame is an invalid input"
```

We don't want to capitalize the first line of an error message.

2024-04-12 08:38 UTC, stinodego requested changes

2024-04-12 08:38 UTC, stinodego commented on py-polars/polars/_utils/parse_expr_input.py
> +    elif isinstance(input, pl.DataFrame):
This is not the right place to add this. It should be added in the `lit` function.

2024-04-12 08:40 UTC, stinodego commented
Maybe this should be parsed as a struct column instead of raising?

2024-04-12 11:43 UTC, deanm0000 commented
> Maybe this should be parsed as a struct column instead of raising?

If they want a struct they can just `df.to_struct()`. I have three reasons for thinking it's not a great idea to do this for people behind the scenes:

1. If they're putting one df as the input to another df's with_columns/select then they're doing an anti-pattern and they should go ask for help so the error is the best thing for them
2. People are likely to be more befuddled by getting a struct where they once got individual columns so it'll feel more like changing behavior without notice than fixing the bug that let them accidentally do the thing.
3. It's a very pandas thing to do to try to anticipate and fix the way people do things incorrectly.

I was scratching my head on suggestions to include in the error message. I was thinking of "hey maybe you need a join or an hstack or to just refactor generally" but there are too many possibilities of what they're doing wrong that I just went with the short one that you see.

2024-04-17 10:25 UTC, closed without merging

2024-04-17 10:25 UTC, stinodego commented
Please see the linked issue. This should not raise.