docs(python): Various deprecation docstring improvements
pola-rs/polars pull request #15648
Opened 2024-04-14 13:16 UTC by henryharbeck

- added "Deprecated since version" to `DataFrame/LazyFrame.with_row_count`
- fix deprecated version in `Expr.str.json_extract`
  -  was discrepancy between decorator and docstring. 0.19.15 is correct.
- do not advise use of deprecated `ambiguous` parameter as a replacement for `use_earliest` parameter in `Series/Expr.dt.truncate`

Drive bys:
- alphabetise `read_clipboard` inside `__all__`
- spelling mistake

2024-04-14 19:29 UTC, alexander-beedie commented on py-polars/polars/expr/datetime.py
> +                This is now auto-inferred, you can safely remove this argument.
```suggestion
                This is now automatically inferred; you can safely omit this argument.
```

2024-04-14 19:30 UTC, alexander-beedie requested changes
Suggest making one minor tweak to the phrasing (in two places), but otherwise looks good to me 😎👍

2024-04-14 19:30 UTC, alexander-beedie commented on py-polars/polars/series/datetime.py
> +                This is now auto-inferred, you can safely remove this argument.
```suggestion
                This is now automatically inferred; you can safely omit this argument.
```

2024-04-15 19:30 UTC, alexander-beedie approved these changes

2024-04-15 20:12 UTC, merged

2024-04-16 12:05 UTC, henryharbeck commented
Thanks for your review @alexander-beedie 
I took the wording from the `ambiguous` parameter below. 
I do like your phrasing better than what was there, so PR incoming to make them consistent!

2024-04-16 12:06 UTC, alexander-beedie commented
> I do like your phrasing better than what was there, so PR incoming to make them consistent!

Nice 😎👍