Add docstring example for DataFrame.limit()
pola-rs/polars pull request #16753
Opened 2024-06-05 20:15 UTC by montanarograziano

Related to: Add missing docstring examples #13161

Add example for:
https://docs.pola.rs/py-polars/html/reference/dataframe/api/polars.DataFrame.limit.html

2024-06-05 20:44 UTC, stinodego requested changes
Thanks - some minor comments on the formatting and this can be merged.

2024-06-05 20:44 UTC, stinodego commented on py-polars/polars/dataframe/frame.py
> +        >>> df = pl.DataFrame(
This needs a blank line or it won't render correctly:

```suggestion
        Get the first 3 rows of a DataFrame.
        
        >>> df = pl.DataFrame(
```

2024-06-05 20:44 UTC, stinodego commented on py-polars/polars/dataframe/frame.py
> +
There should be no blank line at the end:
```suggestion
```

2024-06-06 07:24 UTC, montanarograziano commented
Thank you! I've applied the changes you mentioned.

2024-06-06 08:49 UTC, stinodego approved these changes
Great, thanks!

2024-06-06 08:49 UTC, merged