feat: rename DataFrame.melt to DataFrame.unpivot, and rename its args: id_vars -> index, value_vars -> on
pola-rs/polars pull request #17095
Opened 2024-06-20 15:33 UTC by MarcoGorelli

2024-06-20 22:17 UTC, stinodego requested changes
Whew, quite a lot of churn to get through it looks like!

I know this is still in draft, but I wanted to mention: we should keep `melt` but deprecate it, so we can remove it with 2.0.0.

2024-06-20 22:24 UTC, MarcoGorelli commented
ah sorry, when you said to get rid of `melt` I may have taken you too literally 😄 ok, will update tomorrow to just make it a deprecated alias

2024-06-21 06:47 UTC, JulianCologne commented
Love it! 😄 

Question:
what about the `columns` parameter of `pivot`?
Is this also going to be renamed to `on` like I suggested in my issue?

Asking because the idea was to align the parameters of `pivot`/`unpivot`.

2024-06-21 07:45 UTC, ritchie46 commented
Alright! Ready to undraft?

2024-06-21 07:46 UTC, MarcoGorelli commented
almost, just finishing up `pivot`

2024-06-21 08:30 UTC, MarcoGorelli commented
Sure, done

I do like how it becomes symmetrical, which probably makes things easier for new users, so thanks @JulianCologne for the suggestion. There is some code churn for existing users, but it's a fairly easy find-and-replace

2024-06-21 10:43 UTC, MarcoGorelli commented
For pivot I don't think that can be done in a non-breaking way, at least not without first making the arguments keyword-only. And so if the order in `pivot` stays <index, on>, then it should probably stay that way too in `unpivot`?

2024-06-21 11:01 UTC, stinodego commented
> For pivot I don't think that can be done in a non-breaking way, at least not without first making the arguments keyword-only. And so if the order in `pivot` stays <index, on>, then it should probably stay that way too in `unpivot`?

For pivot, non-keyword args were already deprecated. I had just removed this deprecation for 1.0, so we can change their order without breaking anything right now. So we are really free in determining the most intuitive API here. Would it be better with `on` first?

2024-06-21 11:03 UTC, MarcoGorelli commented
ah, cool! in that case, agree, `on` would look better first

2024-06-21 12:47 UTC, stinodego commented
> not sure I understand sorry - am I OK to make the arguments keyword-only as part of this PR? It still needs enforcing, right?

You don't need to make them keyword-only, you can just move the parameters as you see fit.

If you look at the latest release (0.20.31), you can see that non-keyword arguments were already deprecated:
https://github.com/pola-rs/polars/blob/py-0.20.31/py-polars/polars/dataframe/frame.py#L7561-L7780

So at this point, everyone has their args as keyword arguments. So we are free to move around the parameters as we see fit for the 1.0 release.

2024-06-21 14:07 UTC, MarcoGorelli commented
I feel a bit uneasy about this one, I think it's going to silently break people's code. Though I think the current change in argument order is already going to break it anyway, so let's think if there's a better way

I think the following would feel natural, and would loudly break for anyone who didn't pay attention to their warnings (based on some clients I've worked with, I'd estimate that that's the majority 😩 ):
```python
def pivot(self, on, *, values=None, index=None): ...
```
Then the call becomes:
```
df.pivot('subject', index='name', values=['test_1', 'test_2'])
```
if you don't specify _either_ of `index` or `values`, then all the remaining columns are used for that argument (I think Marshall was suggesting this some time ago). But you need to specify at least one of `index` or `values`

If we could do that, I'd feel a lot easier about changing the order. I also think it would lead to more readable code if `index` and `values` are keyword-only, else `df.pivot('a', 'b', 'c')` could do anything as far as the uninitiated reader is concerned

2024-06-21 14:46 UTC, stinodego commented
Sure that sounds good. Let's do `on, *, index, values` though, because `values` is optional. And `melt` also starts with `on, *, index` then.

2024-06-21 16:37 UTC, MarcoGorelli commented on py-polars/polars/dataframe/frame.py
> +        index: ColumnNameOrSelector | Sequence[ColumnNameOrSelector],
I'm removing the `|None` type hint, as it's not currently supported (will leave that to a separate PR)

2024-06-21 21:31 UTC, stinodego approved these changes
Looks great, thanks Marco!

2024-06-21 21:37 UTC, merged