fix(python): handle '+' on selectors
pola-rs/polars pull request #17117
Opened 2024-06-21 15:28 UTC by coastalwhite

Fixes #13986.

This PR now mirrors the behavior for '|' when trying to add two selectors.

@stinodego can you have a look at this?

2024-06-21 21:26 UTC, stinodego commented
I don't think this is a good idea. You can think of selectors as sets, and you cannot 'add' two sets.

We shouldn't panic of course, but rather throw a helpful error message.

I'll defer to the man himself though: @alexander-beedie

2024-06-21 22:09 UTC, alexander-beedie commented
> I don't think this is a good idea. You can think of selectors as sets, and you cannot 'add' two sets.
> We shouldn't panic of course, but rather throw a helpful error message.

Agreed; selectors combine as set ops, we document them as such[^1], and `+` isn't an alias of `|` for that usage ;)
```python
  File "<ipython-input-7-a082ba43bf67>", line 1, in <module>
    {1,2,3} + {2,3,4}
    ~~~~~~~~^~~~~~~~~
TypeError: unsupported operand type(s) for +: 'set' and 'set'
```

[^1]: https://docs.pola.rs/api/python/stable/reference/selectors.html#set-operations

2024-06-21 22:14 UTC, alexander-beedie requested changes
> I don't think this is a good idea. You can think of selectors as sets, and you cannot 'add' two sets.
> We shouldn't panic of course, but rather throw a helpful error message.

Agreed; selectors combine as set ops, we document them as such[^1], and `+` isn't an alias of `|` for that usage:
```python
>>> {1,2,3} + {2,3,4}
# TypeError: unsupported operand type(s) for +: 'set' and 'set'
```
@coastalwhite: Can you tweak the PR to raise a handy error here instead, perhaps directing the caller to `|`? 👍 

[^1]: https://docs.pola.rs/api/python/stable/reference/selectors.html#set-operations

2024-06-24 07:38 UTC, coastalwhite commented
Okay, did that now. Funnily enough, I originally wrote a patch that threw an exception but changed it for this. So it was just a matter of pressing <kbd>Ctrl</kbd> + <kbd>Z</kbd> a bunch of times.

2024-06-24 10:13 UTC, stinodego reviewed
This fixes the issue for addition, but it feels a bit like a bandaid fix because we'd have to do something like this for all possible unsupported operations. Shouldn't we instead make sure the underlying function throws a nice error instead of panicing?

2024-12-23 07:37 UTC, closed without merging