fixes(rust): slice length deafult None
pola-rs/polars pull request #17372
Opened 2024-07-02 19:27 UTC by sherlockbeard

Fixes: #17365

2024-07-02 20:31 UTC, stinodego approved these changes
Thanks for the fix! Looks correct to me.

2024-07-03 06:41 UTC, ritchie46 requested changes

2024-07-03 06:41 UTC, ritchie46 commented on crates/polars-plan/src/plans/conversion/type_coercion/mod.rs
> +                polars_ensure!(length_dtype.is_integer() || length_dtype.is_null(), InvalidOperation: "length must be integral for slice, not {}", length_dtype);
I think you should negate the check. `!is_null`.

2024-07-03 06:41 UTC, ritchie46 commented on py-polars/tests/unit/expr/test_exprs.py
> +def test_slice() -> None:
Can you test what you want fixed? E.g. ensure that we raise on the invalid input.

2024-07-03 07:01 UTC, ritchie46 commented
Ah, nevermind. I now see the issue. We want `None`.

2024-07-03 07:01 UTC, ritchie46 approved these changes

2024-07-03 07:01 UTC, merged