fix(python): Passthrough sa Connectable
pola-rs/polars pull request #17470
Opened 2024-07-07 08:00 UTC by phi-friday

`pandas` supports `sa.engine.Connectable`.
Passing `sa.engine.Connectable` allows the user to control the transaction.

2024-07-07 09:07 UTC, alexander-beedie commented
I will double-check tonight (on mobile at the moment), but from what I can see this looks like a good addition; thanks!

2024-07-07 15:11 UTC, alexander-beedie requested changes
Let's version-gate the tests, as they don't work on earlier versions of SQLAlchemy, which I sometimes check, as not everyone has moved to v2.0 yet. (The two suggested changes require an additional import `from polars._utils.various import parse_version` at the top of the test module).

Otherwise, looks good to me 👍

2024-07-07 15:11 UTC, alexander-beedie commented on py-polars/tests/unit/io/database/test_write.py
> +@pytest.mark.parametrize("pass_connection", [True, False])
```suggestion
@pytest.mark.parametrize("pass_connection", [True, False])
@pytest.mark.skipif(
    parse_version(sqlalchemy.__version__) < (2, 0),
    reason="requires sqlalchemy >= 2.0",
)
```

2024-07-07 15:11 UTC, alexander-beedie commented on py-polars/tests/unit/io/database/test_write.py
> +@pytest.mark.parametrize("pass_connection", [True, False])
```suggestion
@pytest.mark.parametrize("pass_connection", [True, False])
@pytest.mark.skipif(
    parse_version(sqlalchemy.__version__) < (2, 0),
    reason="requires sqlalchemy >= 2.0",
)
```

2024-07-07 15:45 UTC, phi-friday commented on py-polars/tests/unit/io/database/test_write.py
> +@pytest.mark.parametrize("pass_connection", [True, False])
Fixed test to work with `sqlalchemy<2`.

2024-07-07 15:45 UTC, phi-friday commented on py-polars/tests/unit/io/database/test_write.py
> +@pytest.mark.parametrize("pass_connection", [True, False])
Fixed test to work with `sqlalchemy<2`.

2024-07-07 15:46 UTC, phi-friday commented
Since it's entirely up to the user to control the transaction, I decided it was okay to just modify the test.

2024-07-07 16:09 UTC, phi-friday commented
This is unrelated to this pr, but when I lowered the versions of `sqlalchemy<2` and `pandas<2.2`, I got 3 errors.

```log
FAILED tests/unit/interchange/test_roundtrip.py::test_from_dataframe_pandas_timestamp_ns - AssertionError: DataFrames are different (value mismatch for column 'a')
FAILED tests/unit/io/database/test_read.py::test_read_database_parameterised - sqlalchemy.exc.RemovedIn20Warning: Deprecated API features detected! These feature(s) are not co...
ERROR tests/unit/io/database/test_async.py
```

2024-07-08 07:54 UTC, alexander-beedie commented
> Since it's entirely up to the user to control the transaction, I decided it was okay to just modify the test.

Equally valid ;)

2024-07-08 07:56 UTC, alexander-beedie approved these changes

2024-07-08 07:57 UTC, merged