feat(python): Write format at column level
pola-rs/polars pull request #17757
Opened 2024-07-20 19:18 UTC by mcrumiller

Resolves #17756.

@alexander-beedie I think this is a pretty simple update. If the user specifies a column format, it gets applied at the column level instead of to each individual cell. This has two benefits:

1. The file size will be a little bit smaller when there are many rows, as the format is applied once to the row instead of every single cell.
2. The row-level formats can now be applied after `write_excel` is called. Before, they would not show up at all because cell-level formats override row-level formats.

2024-07-20 19:44 UTC, alexander-beedie commented
Ahh... the contention is that `write_column` actually writes formats at the cell-level? I'm fine with the change if you can make it work - the failing test implies that those formats are not being applied properly to datetime columns (I eyeballed the sheet output 🤔)

2024-07-20 19:49 UTC, alexander-beedie commented on py-polars/polars/dataframe/frame.py
> -                ws.set_column(col_idx, col_idx, None, None, options)
This should be a little cleaner (and still apply the format if there is no option/width):
```python
for c in df.columns:
    col_idx, options = table_start[1] + df.get_column_index(c), {}
    if c in hidden_columns:
        options = {"hidden": True}

    if options or c in column_formats c in column_widths:
        ws.set_column(
            col_idx,
            col_idx,
            column_widths.get(c),
            column_formats.get(c),
            options,
        )`

2024-07-20 19:50 UTC, alexander-beedie commented on py-polars/polars/dataframe/frame.py
>              elif options:
```suggestion
            elif options or fmt:
```

2024-07-20 19:56 UTC, mcrumiller commented
Yeah it does. I'm looking into the date formatting issue, it's coming back as YYYY-MM-DD regardless of output format. I'm off to see a movie now but I'll look into this later.

2024-07-20 20:13 UTC, alexander-beedie commented
> Yeah it does (which is a bit weird, no?).

It's coming back to me now; `write_column` decomposes to cell-level writes, therefore also cell-level formatting: https://xlsxwriter.readthedocs.io/worksheet.html#write_column

> I'm looking into the date formatting issue, it's coming back as YYYY-MM-DD regardless of output format. I'm off to see a movie now but I'll look into this later.

Have fun ;) If you can find a way to address this issue then it looks like a sensible update to me.

2024-07-21 02:20 UTC, mcrumiller commented
An update: it looks like xlswriter `add_table` doesn't like alternative date formats for some reason. I'm looking into converting date/datetimes to [serial dates/datetimes](http://www.cpearson.com/excel/datetime.htm) but I'm not sure if this is too much of a change.

2024-07-21 18:13 UTC, mcrumiller commented
@alexander-beedie I figured it out, and might be useful info for you in the future, and doesn't really make sense hence why it's confusing: when the workbook's `default_date_format` is supplied, it overrides column-level date format. See these examples, three attempts, first two fail.


### (failure) Write data (with no table), set column format

```python
from datetime import date
import xlsxwriter

# specify default workbook date format
wb = xlsxwriter.Workbook("date_format.xlsx", {"default_date_format": "yyyy.dd.mm"})
ws = wb.add_worksheet("Date")

data = [date(2024, 1, 1), date(2024, 1, 2)]
ws.write_column(0, 0, [date(2024, 1, 1), date(2024, 1, 2)])

# assign column format (has no effect)
date_format = wb.add_format({"num_format": "mm-dd-yyyy"})
ws.set_column(0, 0, 10, date_format)

wb.close()
```
Result: column format completely ignored.
![image](https://github.com/user-attachments/assets/da7a6bd6-2ec8-4790-b63b-39885278e950)


### (failure) Write empty table, then write data, then set column format

Next, if we set the default date format, and use `add_table` but add the data later, it still fails, even if we supply a format:

```python
from datetime import date
import xlsxwriter

wb = xlsxwriter.Workbook("date_format.xlsx", {"default_date_format": "yyyy.dd.mm"})
ws = wb.add_worksheet("Date")

data = [[date(2024, 1, 1)], [date(2024, 1, 2)]]
date_format = wb.add_format({"num_format": "mm-dd-yyyy"})
ws.add_table("A1:A2", options={
    "header_row": False,
    "columns": [{"format": date_format}]
})

# write the data afterwards
ws.write_column(0, 0, [date(2024, 1, 1), date(2024, 1, 2)])
ws.set_column(0, 0, 10, date_format)

wb.close()
```
same thing:
![image](https://github.com/user-attachments/assets/eedba583-d05e-4b63-b4eb-077d1df74589)


### (success) Supply the data with the table.

If we supply the data to the `add_table` function, our formatting is finally applied:

```python
from datetime import date
import xlsxwriter

wb = xlsxwriter.Workbook("date_format.xlsx", {"default_date_format": "yyyy.dd.mm"})
ws = wb.add_worksheet("Date")

data = [[date(2024, 1, 1)], [date(2024, 1, 2)]]
date_format = wb.add_format({"num_format": "mm-dd-yyyy"})
ws.add_table(
    "A1:A2",
    options={
        "data": data,  # !!! SEE HERE !!
        "header_row": False,
        "columns": [{"format": date_format}],
    },
)

wb.close()
```
![image](https://github.com/user-attachments/assets/f5614997-e272-4173-bd78-50176b87787b)

I may make a separate PR to move the data writing to the `add_table` function, unless you can recall a reason why that's not the current implementation.

2024-07-22 12:19 UTC, alexander-beedie commented
> Moving the data write to the `add_table` function simplifies everything here (removes a loop) and solves the issue.

Nice discovery - any potential downsides to this approach? (The tests can't really validate formatting, so do we see the expected formatting when eyeballing some of the more sophisticated examples manually? I'll double-check some ;)

2024-07-22 12:29 UTC, mcrumiller commented
I don't think so. The "heavily customized formatting/definition" parameter set in `test_spreadsheet.test_excel_round_trip()` still produces the same result, which is this:

![image](https://github.com/user-attachments/assets/5dc2aa30-9e1d-44f2-85e6-33ed792bbc9a)

which includes the top/bottom formatting, column-specific formatting, and dtype-specific formatting.

Also, I left in the column-formatting section which is probably not strictly necessary any more, I but I feel probably can't hurt if someone decides to manually add data below the table for whatever reason.

2024-07-23 13:17 UTC, alexander-beedie commented
Hmm, I've tested on some other cases and it looks like the new code is not behaving quite the same in several instances - primarily issues with table header.

For example:

```python
pl.DataFrame({
    "id": ["a123", "b345", "c567", "d789"],
    "values": [99, 45, 50, 85],
    "misc": [1.2, 3.4, 5.6, 7.8],
}).write_excel(
    "~/output.xlsx",
    table_style={"style": "Table Style Medium 15"},
)
```

After this patch the second and third column header names end up black for some reason; they do not pick up the table style, which defines them as bold/white, so they look like they aren't there:

![Screenshot 2024-07-23 at 17 14 24](https://github.com/user-attachments/assets/2b61161e-94d7-4916-a61a-7d28f90e989a)

2024-07-23 13:25 UTC, alexander-beedie requested changes
Hmm, I've tested on some other cases and it looks like the new code is not behaving quite the same in several instances - primarily issues with table header.

For example:

```python
pl.DataFrame({
    "id": ["a123", "b345", "c567", "d789"],
    "values": [99, 45, 50, 85],
    "misc": [1.2, 3.4, 5.6, 7.8],
}).write_excel(
    "~/output.xlsx",
    table_style={"style": "Table Style Medium 15"},
)
```

With this patch the second and third column header names end up black; they are present, but do not conform to the given `table_style`, which defines them as bold/white, so they look like they aren't there 🤔

**Before:**

![Screenshot 2024-07-23 at 17 19 08](https://github.com/user-attachments/assets/9c530285-8d73-46a7-b83f-52797cbbb8b6)

**After:**

![Screenshot 2024-07-23 at 17 14 24](https://github.com/user-attachments/assets/2b61161e-94d7-4916-a61a-7d28f90e989a)

Will need some further tinkering :)

(Interestingly there is also a 2-pixel per column increase in column width with the new code, though that's not really important - just an odd observation!)

2024-07-23 13:27 UTC, mcrumiller commented
Thanks--I'll take a look at this tonight and do some more thorough testing.

2024-07-23 14:25 UTC, alexander-beedie commented
Excel is a dark art ;)

2024-07-23 22:18 UTC, mcrumiller commented
@beedie I reproduced, and indeed removing the column formatting fixed it.

I think that we should simply leave the formatting to `add_table`, which seems to be sufficient and simplest. I'll rename the PR since now we're not actually touching the column-level format.

2024-07-24 03:59 UTC, alexander-beedie commented
> @alexander-beedie  I reproduced, and indeed removing the column formatting fixed it.

Nice; will take another run through it today 👍

2024-07-25 11:13 UTC, alexander-beedie approved these changes

2024-07-25 11:14 UTC, alexander-beedie commented
Looks good :)

2024-07-25 11:14 UTC, merged