Attempt to make dtype conversions more centralized
pola-rs/polars pull request #1792
Opened 2021-11-16 19:51 UTC by zundertj

Aims to solve the following:
1. dtype conversions were scattered in multiple places (`datatypes.py`, `series.py`, `frame.py`), now it is all in `datatypes.py`. Note that py_type_to_dtype` still supports a Polars dtype as input, as it is used as such in multiple places. Strictly speaking it should only accept Python types.
2. use dicts rather than long if-else trees
3. break the circular import by factoring out the datatypes for `construction.py` into `datatypes_constructor.py`. Should this be moved into `construction.py`? I think this also removes the need for the `if DOCUMENTING` clause, but I may be wrong here.

Any feedback welcome.

2021-11-16 19:52 UTC, zundertj commented on py-polars/polars/eager/series.py
> -def _maybe_cast(el: "Type[DataType]", dtype: Type) -> "Type[DataType]":
It feels wrong to import a private variable into another module, so I moved this function to `datatypes.py`.

2021-11-16 19:53 UTC, zundertj commented on py-polars/polars/eager/series.py
> +        if return_dtype is None:
In contrast to most other places, `None` is an accepted input here according to the type annotations.

2021-11-16 19:56 UTC, zundertj commented on py-polars/polars/eager/series.py
> -        if dtype == int:
Moved this logic to `datatypes.py`

2021-11-16 19:57 UTC, zundertj commented on py-polars/polars/datatypes.py
> -    "pytype_to_polars_type",
There were two different functions that did more or less the same, hence you will see this rename in a number of places.

2021-11-16 20:02 UTC, ritchie46 requested changes
Most looks good to me! Nice to get a circular import out as well! 

The `DOCUMENTING` clause is still needed. That's because during building of our docs in CI, the polars binaries are not build and the import of `PySeries` and other compiled code fails.

2021-11-16 20:09 UTC, zundertj commented
Added back the `DOCUMENTING` clause, only needed in `datatypes_constructor.py` now, `datatypes` no longer depends on `PySeries`, as it only covers scalars now.

2021-11-16 20:24 UTC, ritchie46 commented
> Added back the `DOCUMENTING` clause, only needed in `datatypes_constructor.py` now, `datatypes` no longer depends on `PySeries`, as it only covers scalars now.

Thanks. I will do a local check for our docs build, just to be sure and then I'll merge.

2021-11-16 20:25 UTC, ritchie46 approved these changes

2021-11-17 07:47 UTC, ritchie46 commented on py-polars/polars/eager/series.py
> -        if dtype == int:
better indeed

2021-11-17 07:56 UTC, ritchie46 commented
The docs build. Again thanks a lot!

2021-11-17 07:56 UTC, merged