perf: Branchless Parquet Prefiltering
pola-rs/polars pull request #19190
Opened 2024-10-11 08:27 UTC by coastalwhite

2024-10-11 09:07 UTC, orlp requested changes

2024-10-11 09:07 UTC, orlp commented on crates/polars-parquet/src/arrow/read/deserialize/primitive/integer.rs
> +        let mut num_read = 0;
I think this loop can be written more efficiently.

```rust
let num_valid = validity.count_ones();
let mut num_written = 0;

while filter != 0 {
    let offset = filter.trailing_zeros();
    validity >>= offset;
    
    let idx = num_valid - validity.count_ones();
    let v = if validity & 1 != 0 {
        dfn.decode(unsafe { values.get_unchecked(idx) })
    } else {
        T::zeroed()
    };

    *out.add(num_written) = v;

    num_written += 1;
    filter >>= offset + 1;
    validity >>= 1;
}

(num_valid, num_written)
```

2024-10-11 09:07 UTC, orlp commented on crates/polars-parquet/src/arrow/read/deserialize/primitive/integer.rs
> +        let mut num_read = 0;
Idem.

2024-10-11 09:07 UTC, orlp commented on crates/polars-parquet/src/arrow/read/deserialize/utils/dict_encoded.rs
> +        let mut num_read = 0;
Idem.

2024-10-11 09:12 UTC, orlp commented on crates/polars-parquet/src/arrow/read/deserialize/primitive/integer.rs
> +        let mut num_read = 0;
Even better I believe:
```rust
let num_available = validity.count_ones();
let mut num_written = 0;

while filter != 0 {
    let offset = filter.trailing_zeros();
    let idx_to_read = num_available - (validity >> offset).count_ones();
    let v = if validity & 1 != 0 {
        dfn.decode(unsafe { values.get_unchecked(idx_to_read) })
    } else {
        T::zeroed()
    };

    *out.add(num_written) = v;
    num_written += 1;
    filter &= filter - 1;
}

(num_available, num_written)
```

2024-10-31 14:55 UTC, coastalwhite commented
ping @ritchie46.

2024-11-01 11:36 UTC, merged