feat: Allow DeltaTable input to scan_delta and read_delta
pola-rs/polars pull request #19229
Opened 2024-10-14 19:50 UTC by deanm0000

https://github.com/pola-rs/polars/issues/19074

2024-10-14 20:39 UTC, alexander-beedie requested changes
A few minor suggestions (typing, error message), but otherwise I think allowing DeltaTable input here makes plenty of sense 👍

2024-10-14 20:39 UTC, alexander-beedie commented on py-polars/polars/io/delta.py
> +                """When supplying a DeltaTable directly, version, storage_options, and delta_table_options are ignored.
```suggestion
                """When supplying a DeltaTable directly, `version`, `storage_options`, and `delta_table_options` are ignored.
```

2024-10-14 20:39 UTC, alexander-beedie commented on py-polars/polars/io/delta.py
```suggestion
    from deltalake import DeltaTable

```

2024-10-14 20:39 UTC, alexander-beedie commented on py-polars/polars/io/delta.py
> +    source: str | deltalake.DeltaTable,
```suggestion
    source: str | DeltaTable,
```

2024-10-14 20:39 UTC, alexander-beedie commented on py-polars/polars/io/delta.py
> +    source: str | deltalake.DeltaTable,
```suggestion
    source: str | DeltaTable,
```

2024-10-14 20:39 UTC, alexander-beedie commented on py-polars/polars/io/delta.py
> +    table_path: str | deltalake.DeltaTable,
```suggestion
    table_path: str | DeltaTable,
```

2024-10-16 12:09 UTC, deanm0000 commented
@alexander-beedie I accepted the tweaks but the code coverage doesn't like it. I'm not sure why, maybe it just needs a retry.

2024-10-17 06:11 UTC, alexander-beedie commented
> @alexander-beedie I accepted the tweaks but the code coverage doesn't like it. I'm not sure why, maybe it just needs a retry.

Yup, those failures are unrelated.

2024-10-17 06:11 UTC, alexander-beedie approved these changes

2024-10-17 06:12 UTC, merged