feat: Added `escape_regex` operation to the `str` namespace and as a global function
pola-rs/polars pull request #19257
Opened 2024-10-16 10:45 UTC by barak1412

Fixes https://github.com/pola-rs/polars/issues/19207.

2024-10-16 10:50 UTC, barak1412 commented
@orlp Just to be sure -

The code:

```python
import polars as pl

df = pl.DataFrame({"text": ["abc", "def", None, "abc(\\w+)"]})

df.with_columns(escaped=pl.escape_regex('text'))
```

Should escape the `'text'` literal, not the column, right?

Besides, I need to:
1. Add tests.
2. Add `pl.escape_regex` as function.
3. Refactor the code such that the namespace `Expr` will be translated to the function `Expr`.

2024-10-16 11:09 UTC, orlp commented
@barak1412 `pl.escape_regex` should *only* work on Python strings, and not interact with the expression API at all. I would suggest adding a warning/error if you try to pass in an expression into it, suggesting you to use `Expr.str.escape_regex` instead.

2024-10-18 07:10 UTC, barak1412 commented on crates/polars-ops/src/chunked_array/strings/escape_regex.rs
> +pub fn escape_regex_str(s: &str) -> String {
Added this function so `pl.escape_regex` and `str.escape_regex` will be coupled by same implementation.

2024-10-18 07:36 UTC, barak1412 commented
@orlp I will be glad if you can look, thanks.

2024-10-18 10:10 UTC, orlp requested changes

2024-10-18 10:10 UTC, orlp commented on crates/polars-ops/src/chunked_array/strings/escape_regex.rs
> +    unary_elementwise(ca, escape_regex_helper)
Can you add a dependency on `regex_syntax` (we already have this indirectly), and use a loop similar to this?

```rust
pub fn escape_regex(ca: &StringChunked) -> StringChunked {
    let mut buffer = String::new();
    let mut builder = StringChunkedBuilder::new(ca.name().clone(), ca.len());
    for opt_s in ca.iter() {
        if let Some(s) = opt_s {
            buffer.clear();
            regex_syntax::escape_into(s, &mut buffer);
            builder.append_value(&buffer);
        } else {
            builder.append_null();
        }
    }
}
```

This prevents us from having to allocate for each string.

2024-10-18 10:10 UTC, orlp commented on py-polars/polars/functions/escape_regex.py
> +        msg = "escape_regex function is unsupported for `Exp`, you may want use `Expr.str.escape_regex` instead"
Typo: `Exp` -> `Expr`.

2024-10-19 17:11 UTC, barak1412 commented
@orlp Should be the right fix now, thanks.

2024-10-19 20:28 UTC, orlp approved these changes

2024-10-21 08:56 UTC, ritchie46 commented
Looks great @barak1412, we only miss docs entries in the python reference guide. Then it is good to go.

2024-10-21 10:10 UTC, barak1412 commented
@ritchie46 Sure, added to the docs.

I hope I changed the right places, first time I am touching the docs.

2024-10-22 17:27 UTC, ritchie46 commented
Thanks @barak1412

2024-10-22 17:27 UTC, merged