docs: Update Excel page of user guide to refer to fastexcel as the default engine
pola-rs/polars pull request #19691
Opened 2024-11-07 16:58 UTC by braaannigan

The user guide page for Excel files has not been updated to account for calamine as the default reader. The PR updates the page along with some minor edits

2024-11-07 17:32 UTC, alexander-beedie requested changes
Good catch; just a minor nit :)

2024-11-07 17:32 UTC, alexander-beedie commented on docs/source/user-guide/io/excel.md
> +We recommend working with the default fastexcel engine. The xlsx2csv and openpyxl engines are slower but do have more features for parsing tricky data. These engines may be helpful if the fastexcel r
```suggestion
We recommend working with the default fastexcel engine. The xlsx2csv and openpyxl engines are slower but may have more features for parsing tricky data. These engines may be helpful if the fastexcel reader does not work for a specific Excel file.
```

2024-11-07 17:32 UTC, alexander-beedie commented on docs/source/user-guide/io/excel.md
> +We recommend working with the default fastexcel engine. The xlsx2csv and openpyxl engines are slower but do have more features for parsing tricky data. These engines may be helpful if the fastexcel r
Let's soften that one a bit; the `fastexcel`  folks have added quite a few features over the last few months and it's getting pretty fully featured :)

2024-11-08 06:53 UTC, alexander-beedie commented on docs/source/user-guide/io/excel.md
> +- fastexcel: This reader is based on the Rust [calamine](https://github.com/tafia/calamine) crate and is typically the fastest reader.
```suggestion
- fastexcel: This engine is based on the Rust [calamine](https://github.com/tafia/calamine) crate and is (by far) the fastest reader.
```

2024-11-08 06:55 UTC, alexander-beedie approved these changes

2024-11-08 07:40 UTC, braaannigan commented
@alexander-beedie am I right that you don't need anything further from me on this? Not sure why that test is failing, the rust analyser link works when I try it.

2024-11-08 08:08 UTC, alexander-beedie commented
> @alexander-beedie am I right that you don't need anything further from me on this? Not sure why that test is failing, the rust analyser link works when I try it.

Yup, I think it's good to merge - also not sure why that error appeared :\

2024-11-08 08:24 UTC, merged