fix(python): typing for `Series` methods that can return `None`
pola-rs/polars pull request #6690
Opened 2023-02-05 16:10 UTC by MatveyF

Resolves #6623 

Fix the type hints for some `Series` methods that return `None`.

2023-02-06 05:44 UTC, alexander-beedie commented
Nice; FYI, as the tests have to run on python 3.7, you can't use the walrus operator `:=` ;)

2023-02-06 08:18 UTC, MarcoGorelli requested changes
Hi @MatveyF 

Sorry to jump in, just wanted to point out that this would break the following:
```python
result = pl.date_range(datetime(1969, 12, 31), datetime(1970, 1, 2), "1d").dt.median()
assert result == datetime(1970, 1, 1)
```
You probably need to explicitly check `if out is not None` rather than just `if out`

2023-02-07 11:12 UTC, MarcoGorelli commented
Nice! I think you also fixed a bug here - the following fails on `master`
```python
In [4]: pl.Series([None]).cast(pl.Datetime).dt.median()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In [4], line 1
----> 1 pl.Series([None]).cast(pl.Datetime).dt.median()

File ~/tmp/.venv/lib/python3.8/site-packages/polars/internals/series/datetime.py:94, in DateTimeNameSpace.median(self)
     74 """
     75 Return median as python DateTime.
     76
   (...)
     91
     92 """
     93 s = pli.wrap_s(self._s)
---> 94 out = int(s.median())
     95 return _to_python_datetime(out, s.dtype, s.time_unit)

TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```
but works in your branch. Might be worth adding it as a test case to make sure nobody accidentally brings it back in the future?

2023-02-07 11:44 UTC, MarcoGorelli approved these changes
No objections, over to maintainers (test could be parametrised, something like
```python
@pytest.mark.parametrize(
    ('value', 'expected'),
    [(dt.datetime(1970, 1, 1), (dt.datetime(1970, 1, 1)], [None, None])
)
def test_median(value, expected) -> None:
    result = pl.Series([value]).cast(pl.Datetime).dt.median()
    assert result == expected
```
, but I might be nitpicking here 😄 )

2023-02-07 17:21 UTC, merged