perf(python): Improve performance of `expr_to_lit_or_expr` for arguments of type `Expr` by ~80%
pola-rs/polars pull request #6967
Opened 2023-02-17 15:20 UTC by jakob-keller

`expr_to_lit_or_expr` is used extensively throughout the codebase. When providing arguments of type `Expr` in an attempt to improve performance, the current implementation can do better IMO.

Benchmark

```
python3 -m timeit -s "import polars; expr = polars.col('test')" "polars.internals.expr_to_lit_or_expr(expr)"
```

0.16.6: `351 nsec per loop`
After PR: `74.1 nsec per loop`

2023-02-17 21:24 UTC, stinodego requested changes
Fair addition. But please change the final `elif not isinstance(expr, Expr)` line to `else`. Then this can be merged.

I will probably revise this parsing logic in the near future, but this is a good thing to consider.

2023-02-17 21:38 UTC, stinodego approved these changes
Thanks! Good addition. Expression inputs should be the default, anything else could be considered an ergonomic shortcut. So I think it's good to give 'preferential treatment' to expressions here.

2023-02-17 21:48 UTC, jakob-keller commented
> Thanks! Good addition. Expression inputs should be the default, anything else could be considered an ergnomic shortcut. So I think it's good to give 'preferential treatment' to expressions here.

Thanks for the speedy review!

If the `polars` community is interested, I might suggest a number of similar improvements. At the moment, I am mostly using the low-level Python bindings (in polars.polars), since the high-level Python wrappers are not performant enough for particular my use case (high-frequency, real-time feature building for use in ML inference). If I could remove the main performance issues, I could use the regular Python API and be happy.

2023-02-17 22:15 UTC, stinodego commented
I'd be very interested in your input. Feel free to create an issue for this to start a discussion and track progress on similar improvements, or just send some more PRs our way!

2023-02-18 05:55 UTC, merged

2023-02-19 14:12 UTC, jakob-keller commented
> I'd be very interested in your input. Feel free to create an issue for this to start a discussion and track progress on similar improvements, or just send some more PRs our way!

There you go: #7019, #7020