Easier subclassing
pola-rs/polars pull request #7426
Opened 2023-03-08 14:25 UTC by ml31415

Referring to https://github.com/pola-rs/polars/issues/7200 that's a possibility how `DataFrame` and `Series` would be easier to subclass. Previous test cases pass untouched, test cases for subclassing got added, but could still need some extension.

2023-03-09 06:14 UTC, stinodego requested changes
At first glance, I have a bunch of remarks on the implementation side of this PR. But I'd like to see an agreement in the related issue before I do a full review, as it might turn out we do not want this functionality at all.

2023-03-09 10:07 UTC, stinodego requested changes
There are a lot of implementation issues with this PR. I don't really know where to start. I left a few comments, but it is not a comprehensive review.

I think the main issue is that this PR promises easier subclassing, but doesn't really deliver on that promise, while adding a lot of clutter and making the code less readable.

The goal of this PR is a noble one. In the existing code base, subclassing sort-of works, but is very limited. Some operations preserve the subclass, while others do not. I recently made some improvements in this regard (see https://github.com/pola-rs/polars/pull/6882), but to be fair, we're not at a point yet where we can say that we offer reliable subclassing support.

If we merge this PR, we would be making some concessions in code readability, but still cannot claim to have a working subclassing implementation. Most importantly, using namespace methods still won't preserve subclasses.

To improve subclassing, the following would be top-of-mind for me:

Make namespaces generic over the Series/Expr they originate from (similar to GroupBy). This allows preserving subclasses in namespace methods.
Update the Series dispatch decorator to preserve subclass.
Address some stray methods that could preserve subclass but currently do not for whatever reason.
Make sure every relevant method returns Self and passes type checking.
Make sure this feature gets documented somewhere.
These are steps we can take without making any concessions in code readability/quality. As it stands, I am not eager to make any concessions since none of us seem too enthousiastic about the pattern described in the linked issue.

2023-03-09 12:00 UTC, ml31415 commented on py-polars/polars/internals/dataframe/frame.py
> +
It was supposed to serve as a replacement for `wrap_df` on class level, equivalent to the classmethod `wrap_s` for the series.

2023-03-09 12:07 UTC, ml31415 commented on py-polars/polars/internals/series/series.py
> +        return self.wrap_s(self._s.bitxor(other._s))
As far as I understood the typing syntax, it should be fine to have `Series` there, as long as anything returned is a subclass of it. If it's supposed to be changed to `Self`, that would apply to many other methods as well.

2023-03-09 13:01 UTC, ml31415 commented on py-polars/polars/internals/dataframe/frame.py
> +            other = type(self)([s.rename(f"n{i}") for i in range(len(self.columns))])
It's the standard way of accessing a type from inside of the class definition, less error prone than `self.__class__` and IMHO rather commonly used. I'd rather argue, that using the class name to access the type without good reason (like in the instance check above) is a violation of the clean code principle 'don't repeat yourself'. So I don't see anything to improve here.

2023-03-09 15:22 UTC, kylebarron commented on py-polars/polars/internals/series/series.py
> +        return self.wrap_s(self._s.bitxor(other._s))
In general with these type of methods, if you pass in a specific subclass of a `Series`, you probably want to get that exact same subclass type back. `Self` type exists to support this: https://peps.python.org/pep-0673/

In this specific case, not sure how that interacts with `other` and what type `other` is allowed to be.

2023-03-09 22:56 UTC, stinodego commented
@ml31415 I've briefly discussed with Ritchie, and I don't really want to go ahead with this until we have a clearer vision on how we want to approach interoperability. So let's put a pin in this for now, and we'll get back to issue #7200 in the near future.

2023-03-20 08:48 UTC, ritchie46 commented
I will close this as I don't think we should have inheritance on our types. Discussion can continue in https://github.com/pola-rs/polars/issues/7200

2023-03-20 08:48 UTC, closed without merging