Use schema keys as columns if only schema provided to struct
pola-rs/polars pull request #8952
Opened 2023-05-20 17:30 UTC by mcrumiller

Resolve #8951.

When calling `pl.struct(...)` with a schema, the user shouldn't have to redundantly supply the column names if the schema defines the struct by itself:

```python
# this fails, but it shouldn't
import polars as pl

df = pl.DataFrame(
    {
        "a": [1, 2, 3],
        "b": [4, 5, 6],
    }
).select(
    pl.struct(schema={
        "a": pl.UInt8,
        "b": pl.Float32,
    }).alias("struct")
)
```

I think we should still keep the `schema` keyword as required, otherwise our `exprs` argument will have to have a bunch of additional type logic and it'll get messy.

2023-05-20 18:51 UTC, alexander-beedie commented
Nicely done; this looks good to me - don't forget to use scoped [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) on your PRs ;)

2023-05-20 18:52 UTC, alexander-beedie approved these changes

2023-05-20 18:53 UTC, mcrumiller commented
Thanks for the link @alexander-beedie, sorry about that!

2023-05-20 18:54 UTC, alexander-beedie commented
> Thanks for the link @alexander-beedie, sorry about that!

@mcrumiller: No problem; before merging, can you add some test coverage?
Doesn't need much, but at least one is necessary ;)

2023-05-20 18:54 UTC, alexander-beedie requested changes
Looks good, but needs a unit test ;)

2023-05-20 19:27 UTC, mcrumiller commented
Added unit test.

2023-05-20 19:35 UTC, alexander-beedie approved these changes

2023-05-20 19:35 UTC, merged

2023-05-20 19:36 UTC, mcrumiller commented
Ahh I just noticed a couple comments in the test that aren't applicable (I had syntax errors in my test that I initially faulted polars for). Let me make a quick follow-up PR. Sorry about that.

2023-05-29 20:28 UTC, jonashaag commented
@mcrumiller do you think we should prevent this?

```py
pl.DataFrame({"x": 42}).select(pl.struct({"x": pl.Int8}))
```

This seems to simply ignore the first argument with no error or warning.

2023-05-29 21:05 UTC, mcrumiller commented
Yeah, I wasn't aware a dict would work directly anyway. On looking into it, it looks like we have an issue where dictionarys are interpreted as column lists, I'll create a new issue for this.