feat(python): Add pyarrow write_to_dataset to write_parquet function
pola-rs/polars pull request #9835
Opened 2023-07-12 13:14 UTC by potzenhotz

Implements [#9812](https://github.com/pola-rs/polars/issues/9812)

Currently Polars uses _pyarrow.write_table()_ to write parquets with pyarrow. The _pyarrow.write_to_dataset()_ funtion is not used. 
_pyarrow.write_to_dataset()_ does support more features than _write_table()_. Important features like writing partitioned parquet files.
Therefore, I added _pyarrow.write_to_dataset()_ using a new parameter in write_parquet(), namely "use_pyarrow_write_to_dataset".

I added two tests and an example in the docstring.
Currently some parameters like statistics or compressions are not used when calling _write_to_dataset()_ as these are not supported in _write_to_dataset()_.

Links:

- https://arrow.apache.org/docs/python/generated/pyarrow.parquet.write_to_dataset.html

2023-07-12 16:18 UTC, alexander-beedie commented
Hmm… If this function represents a superset of `write_table` then we should consider replacing the existing call instead of supporting both and adding an extra parameter.

I’m on a train at the moment, but reading through the linked docstring it seems like the `**kwargs` allow pass-through options to the underlying parquet writes that would include compression/etc?

2023-07-12 17:48 UTC, potzenhotz commented
Hey @alexander-beedie,

so this was my first idea using use_legacy_dataset=True as default so that write_table is used and setting use_legacy_dataset=False when pyarrow.write_to_dataset should be used.
But, we get a dprecation warning from pyarrow as it is not supported in the future (https://github.com/apache/arrow/issues/32067) 
`FutureWarning: Passing 'use_legacy_dataset=True' to get the legacy behaviour is deprecated as of pyarrow 11.0.0, and the legacy implementation will be removed in a future version.`

Therefore, I left write_table() unchanged.

I added the compression, statistic etc. fields to the to pyarrow_options and edited one of the test cases.

Do we need further tests or code changes? 
Thanks for the fast response already.

2023-07-13 01:05 UTC, erinov1 commented
Even in the case of no partitioning columns, `write_to_dataset` creates a data directory with a parquet file named `<uuid>-0.parquet`. In other words, `df.write_parquet("test.parquet", use_pyarrow_write_to_dataset=True)` would write a directory while `df.write_parquet("test.parquet", use_pyarrow_write_to_dataset=False)` would write a single file. If this proposal is adopted then the docs should reflect the difference.

2023-07-13 06:23 UTC, potzenhotz commented
Hey, thats true but the same behaviour as Spark which is a almost standard in Cloud ETL.
I added two more lines in the description.

2023-07-13 20:45 UTC, alexander-beedie commented
Ok; let's see how this looks instead - rather than have another (long!) parameter called `use_pyarrow_write_to_dataset`, it could be a lot cleaner to automatically use `write_to_dataset` _if_ the user supplies "partition_cols" to the pyarrow options dict (obviously keeping/tweaking the docs to make it clear that this is what happens). It keeps the simplicity of a single param and it feels fairly intuitive - the caller doesn't need to switch between different functions themselves as their given options should imply which one should be used 🤔

2023-07-14 06:53 UTC, potzenhotz commented
Fair argument. I changed the code accordingly.

2023-07-25 09:42 UTC, potzenhotz commented
Hey @alexander-beedie is there anything futher to change? Are there any plans to integrate te change?

Thanks.

2023-07-25 09:49 UTC, alexander-beedie commented
> Hey @alexander-beedie is there anything futher to change? Are there any plans to integrate te change?

Ahh, great - I didn't spot that you had made the update - will take a look :)

2023-07-25 14:59 UTC, alexander-beedie requested changes
If you can update `test_write_parquet_using_pyarrow_write_to_dataset_with_partitioning` as requested, should be good to go 👍

2023-07-26 15:59 UTC, uditrana commented
Have been looking for this feature! Hope to see it added soon.

2023-07-27 17:49 UTC, potzenhotz commented on py-polars/tests/unit/io/test_parquet.py
> +def test_write_parquet_using_pyarrow_write_to_dataset_with_partitioning(
Enhanced the test case by reading the written parquets and asserted them.

2023-07-31 06:11 UTC, alexander-beedie approved these changes

2023-07-31 06:11 UTC, merged

2023-07-31 06:11 UTC, alexander-beedie commented
Thanks!

2023-08-08 07:56 UTC, potzenhotz commented
Thanks for the great feedback and communication!